apiVersion: v1
kind: Service
metadata:
  name: discounts-service
  labels:
    app: discounts-service
spec:
  type: ClusterIP
  selector:
    app: discounts
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002