apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: romainconfavreux/restauranty_auth:latest
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: auth-secrets