apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restauranty-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /api/auth/*
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3001
          - path: /api/discounts/*
            pathType: Prefix
            backend:
              service:
                name: discounts-service
                port:
                  number: 3002
          - path: /api/items/*
            pathType: Prefix
            backend:
              service:
                name: items-service
                port:
                  number: 3003
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 3000
