apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: romainconfavreux/restauranty_client:latest
          ports:
            - containerPort: 80
          command: ["/bin/sh"]
          args: ["/scripts/env-replace.sh"]
          volumeMounts:
            - name: env-replace-script
              mountPath: /scripts
      volumes:
        - name: env-replace-script
          configMap:
            name: env-replace-script
            defaultMode: 0755
